name: actors_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_swiper: ^1.1.6
  http: ^0.12.2
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.3.2

flutter:
  uses-material-design: true
  assets:
   - assets/img/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"

flutter_native_splash:
  background_image: "assets/img/logo.png"
  android: true